== copyright-statement
=== Copyright notice

[align="center"]
Copyright © {{ docyear }} {{ copyright_holder }} +
To obtain additional rights of use, visit
https://www.ogc.org/legal[]

=== Note
[align="left"]
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

[align="left"]
Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

== license-statement
=== License Agreement

Use of this document is subject to the license agreement at https://www.ogc.org/license[]

== legal-statement
{% if doctype == "Standard" or doctype == "Community Standard" or doctype == "Abstract Specification" %}
{% if stage == "Deprecated" %}

=== Notice
This Standard has been deprecated by the OGC and is no longer supported. A newer version exists and is recommended for use. This document is available on a royalty free, non-discriminatory basis.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% elsif stage == "Legacy" %}

=== Notice
This Standard has been deprecated to Legacy status and is no longer supported. This Standard is still suitable for use, but newer Standards offer the same or improved functions and capabilities. This document is available on a royalty free, non-discriminatory basis.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% elsif stage == "Rescinded" %}

=== Notice
This Standard has been rescinded and is no longer an OGC Standard nor is it suitable for use. Rescinded Standards are not published on any public OGC resources.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% elsif stage == "Retired" %}

=== Notice
This Standard has been retired by the OGC and is no longer supported nor recommended for use. This document is available on a royalty free, non-discriminatory basis.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% elsif stage == "Approved" or stage == "Withdrawn" %}

=== Notice
This document is an OGC Member approved international standard. This document is available on a royalty free, non-discriminatory basis. Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% else %}
=== Notice for Drafts
This document is not an OGC Standard. This document is distributed for review and comment. This document is subject to change without notice and may not be referred to as an OGC Standard.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.
{% endif %}


{% elsif doctype == "Engineering Report" %}
=== Notice
This document is not an OGC Standard. This document is an OGC Public Engineering Report created as a deliverable in an OGC Interoperability Initiative and is _not an official position_ of the OGC membership. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an OGC Standard.

Further, any OGC Engineering Report should not be referenced as required or mandatory technology in procurements. However, the discussions in this document could very well lead to the definition of an OGC Standard.


{% elsif doctype == "Best Practice" %}
=== Notice
This document defines an OGC Best Practice on a particular technology or approach related to an OGC standard. This document is _not_ an OGC Standard and may not be referred to as an OGC Standard. It is subject to change without notice. However, this document is an _official_ position of the OGC membership on this particular technology topic.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

{% elsif doctype == "Release Notes" %}
=== Notice
This document is not an OGC standard. This document provides release notes for an OGC standard. This document is subject to change without notice and may not be referred to as an OGC Standard.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.


{% else %}
=== Notice
This document is not an OGC Standard. This document is an OGC {{ doctype }} and is therefore not an official position of the OGC membership. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an OGC Standard.

Further, an OGC {{ doctype }} should not be referenced as required or mandatory technology in procurements.

{% endif %}





== feedback-statement
{% if doctype == "Standard" %}
[[boilerplate-standard-feedback]]
=== {blank}
Suggested additions, changes and comments on this document are welcome and encouraged. Such suggestions may be submitted using the online change request form on OGC web site: http://ogc.standardstracker.org/[]
{% endif %}
